return {
  -- 'folke/snacks.nvim',
  -- priority = 1000,
  -- lazy = false,
  -- opts = {
  --   bigfile = { enabled = true },
  --   dashboard = {
  --     enabled = true,
  --     sections = {
  --       { section = 'header' },
  --       { section = 'keys', gap = 1, padding = 1 },
  --       { section = 'startup' },
  --       -- {
  --       --   section = 'terminal',
  --       --   cmd = 'pokemon-colorscripts -r --no-title; sleep .1',
  --       --   random = 10,
  --       --   indent = 10,
  --       --   height = 20,
  --       -- },
  --     },
  --   },
  --   notifier = { enabled = true, timeout = 3000 },
  --   quickfile = { enabled = true },
  --   statuscolumn = { enabled = true },
  --   words = { enabled = true },
  -- },
  -- keys = {
  --   {
  --     '<leader>n',
  --     function()
  --       Snacks.notifier.show_history()
  --     end,
  --     desc = 'Notification History',
  --   },
  -- },
}
